### ISSUE TITLE
[Suggestion] Noise seed

### ISSUE THREAD

**Issue by Bamboy** [heyx3/GPUNoiseForUnity#5]
As a noise generation utility, I am really suprised this isnt in here already. 
Add the ability to specify what seed to use when generating noise. (Perhaps it would be best if this was a hard-coded int scalar param?)

**Comment by heyx3** [comment]
You can currenrly incorporate a seed by adding an extra dimension to the noise, using the seed as that extra dimension value. You could also add or multiply the seed value with the input into the noise function.

However, it's probably a good idea to add a built-in "seed" param that is used in the basic float-hashing functions underlying all noise generation. I'll do that asap.

On an unrelated note, I'm sorry I didn't see your contributions earlier! This is basically the first time other people have contributed to my repo.

**Comment by heyx3** [comment]
Sorry, I hit the wrong button and I'm on mobile; let me finish my comment:

I'm sorry I didn't see your contributions earlier! This is basically the first time other people have contributed to my repo.

**Comment by heyx3** [comment]
35ad5192abe2f5ebe27e52ae635866351827ee0e added support for a UV Z coordinate, which can easily be used as a seed.
